project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.static import serve
from django.urls import include, path, re_path

from . import views
from .decorators import logged_out_required

urlpatterns = [
    path('', include('workouttracker.urls')),
    path('login/', logged_out_required(views.LoginView.as_view()), name='login'),
    path('logout/', login_required(views.LogoutView.as_view(), login_url="/login/"), name='logout'),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

workouttracker/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('', login_required(views.IndexView.as_view(), login_url="/login/"), name='index'),
    path('workout_start', login_required(views.WorkoutStartView.as_view()), name="workout_start"),
    path('workout/<int:pk>/', login_required(views.WorkoutView.as_view()), name='workout'),
    path('workout/<int:workout_id>/add_exercise/', login_required(views.WorkoutAddExerciseView.as_view()), name='workout_add_exercise'),
    path('workout/update_exercise/<int:pk>/', login_required(views.WorkoutUpdateExerciseView.as_view()), name='workout_update_exercise'),
    path('workout/increment_exercise_sets/<int:pk>/', login_required(views.WorkoutIncrementExerciseSetsView.as_view()), name='workout_increment_exercise_sets'),
    path('workout/<int:pk>/end/', login_required(views.WorkoutEndView.as_view()), name='workout_end'),
    path('workout/previous_list/', login_required(views.WorkoutPreviousListView.as_view()), name='workout_previous_list'),
    path('exercise_list/', login_required(views.ExerciseListView.as_view()), name='exercise_list'),
    path('exercise_create/', login_required(views.ExerciseCreateView.as_view()), name='exercise_create'),
    path('exercise_update/<int:pk>/', login_required(views.ExerciseUpdateView.as_view()), name='exercise_update'),
    path('exercise_delete/<int:pk>/', login_required(views.ExerciseDeleteView.as_view()), name='exercise_delete'),
    path('statistics/', login_required(views.StatisticsView.as_view()), name='statistics'),
    path('statistics/exercise_data_points/<int:pk>/', login_required(views.StatisticsExerciseDataPointsView.as_view()), name='statistics_exercise_data_points'),
]

workouttracker/models.py
from math import floor

from django.db import models
from django.templatetags.static import static

class Exercise(models.Model):
    name = models.CharField(max_length=100)

    class Category(models.TextChoices):
        CARDIO_MACHINE = ("C", "Cardio machine")
        RESISTANCE_MACHINE = ("R", "Resistance machine")
        FREE_WEIGHTS = ("F", "Free weights")
        OTHER = ("O", "Other")

    category = models.CharField(max_length=1, choices=Category.choices, default=Category.CARDIO_MACHINE)

    weight_measured = models.BooleanField(default=False, verbose_name="Is this exercise measured by weight?")
    reps_measured = models.BooleanField(default=False, verbose_name="Is this exercise measured by number of repetitions?")
    duration_measured = models.BooleanField(default=False, verbose_name="Is this exercise measured by its duration?")
    distance_measured = models.BooleanField(default=False, verbose_name="Is this exercise measured by distance?")
    difficulty_level_measured = models.BooleanField(default=False, verbose_name="Is this exercise measured by difficulty level?")
    image = models.ImageField(null=True, blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ["category", "name"]

    def __str__(self):
        return self.name
    
    def get_image_url(self):
        if self.image:
            return self.image.url
        else:
            return static("workouttracker/Black square.png")
        
    @staticmethod
    def get_all_metric_fields():
        return ["weight", "reps", "duration", "distance", "difficulty_level"]
    
    def get_enabled_metric_fields(self):
        enabled_metric_fields = []
        if self.weight_measured:
            enabled_metric_fields.append("weight")
        if self.reps_measured:
            enabled_metric_fields.append("reps")
        if self.duration_measured:
            enabled_metric_fields.append("duration")
        if self.distance_measured:
            enabled_metric_fields.append("distance")
        if self.difficulty_level_measured:
            enabled_metric_fields.append("difficulty_level")
        return enabled_metric_fields



class Workout(models.Model):
    start_dt = models.DateTimeField()
    end_dt = models.DateTimeField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True, verbose_name="Weight (kgs)")
    
    class Meta:
        ordering = ["start_dt"]

    def __str__(self):
        return f"Workout on {self.start_dt.date().strftime('%d-%m-%Y')} at {self.start_dt.strftime('%H:%M')}"
    
    def is_complete(self):
        return bool(self.end_dt)
    
    def get_length(self):
        return floor((self.end_dt - self.start_dt).seconds / 60) if self.end_dt else 0
    

class WorkoutExercise(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.deletion.CASCADE)
    workout = models.ForeignKey(Workout, on_delete=models.deletion.CASCADE)
    weight = models.FloatField(null=True, blank=True, verbose_name="Weight (kgs)")
    reps = models.IntegerField(null=True, blank=True, verbose_name="Repetitions")
    duration = models.DurationField(null=True, blank=True, help_text="05:00 is five minutes. 01:00:00 is one hour.")
    distance = models.IntegerField(null=True, blank=True, verbose_name="Distance (metres)")
    difficulty_level = models.IntegerField(null=True, blank=True)
    sets = models.IntegerField(default=1)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.exercise.name} on {self.workout.start_dt.date().strftime('%d-%m-%Y')}"
    
    def get_metric_values(self):
        metric_values = {}
        for metric_field in self.exercise.get_enabled_metric_fields():
            metric_values[metric_field] = getattr(self, metric_field)
        return metric_values

workouttracker/forms.py
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Submit, HTML, Field
from django import forms
from django.urls import reverse_lazy

from project.forms import FormWithHelperMixin
from workouttracker.utils import get_enabled_metric_fields_by_exercise
from .models import Exercise, WorkoutExercise


class ExerciseForm(FormWithHelperMixin, forms.ModelForm):
    class Meta:
        model = Exercise
        fields = [
            "name",
            "category",
            "weight_measured",
            "reps_measured",
            "duration_measured",
            "distance_measured",
            "difficulty_level_measured",
            "image",
            "notes",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout.append(Submit('submit', self.submit_text, css_class=self.submit_css_class))
        if self.instance.pk:
            self.helper.layout.append(HTML(f"<a class='btn btn-danger{' disabled' if self.instance.workoutexercise_set.exists() else ''}' href='{reverse_lazy('exercise_delete', kwargs={'pk': self.instance.pk})}'>Delete</a>"))


class WorkoutExerciseForm(FormWithHelperMixin, forms.ModelForm):
    class Meta:
        model = WorkoutExercise
        fields = [
            "exercise",
            "weight",
            "reps",
            "duration",
            "distance",
            "difficulty_level",
            "sets",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        all_metric_fields = Exercise.get_all_metric_fields()
        if self.instance.pk:
            self.fields.pop("exercise")
            enabled_metric_fields = self.instance.exercise.get_enabled_metric_fields()
            for field in all_metric_fields:
                if field not in enabled_metric_fields:
                    self.fields.pop(field)
        layout = Layout(
            "exercise",
            HTML(f"""<div id='div_notes' class='fw-light fst-italic mb-3' style='white-space: pre-wrap'>{self.instance.exercise.notes if self.instance.pk and self.instance.exercise.notes else ""}</div>"""),
            *[Field(metric_field) if metric_field in self.fields else None for metric_field in all_metric_fields],
            HTML("<hr/>"),
            "sets",
            Submit('submit', self.submit_text, css_class=self.submit_css_class)
        )
        self.helper = FormHelper(self)
        self.helper.layout = layout


class WorkoutEndForm(FormWithHelperMixin, forms.ModelForm):
    submit_text = "End workout"
    submit_css_class = "btn-success w-100"

    class Meta:
        model = WorkoutExercise
        fields = [
            "weight",
        ]

workouttracker/views.py
from django.http.response import HttpResponse as HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic

from workouttracker.templatetags.workout_extras import capitalise_and_underscore_to_space

from .forms import ExerciseForm, WorkoutEndForm, WorkoutExerciseForm
from .models import Exercise, Workout, WorkoutExercise
from .utils import get_default_metric_values_by_exercise, get_enabled_metric_fields_by_exercise, get_notes_by_exercise

class IndexView(generic.TemplateView):
    template_name = "workouttracker/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_workout"] = Workout.objects.filter(end_dt__isnull=True).first()
        return context
    

class WorkoutStartView(generic.RedirectView):
    pattern_name = "workout"

    def get_redirect_url(self, *args, **kwargs):
        workout = Workout.objects.filter(end_dt__isnull=True).first()
        if not workout:
            workout = Workout.objects.create(start_dt=timezone.now())
        kwargs["pk"] = workout.pk
        return super().get_redirect_url(*args, **kwargs)
    

class WorkoutView(generic.DetailView):
    template_name = "workouttracker/workout/workout.html"
    model = Workout


class WorkoutAddExerciseView(generic.CreateView):
    template_name = "workouttracker/workout/workout_exercise_form.html"
    model = WorkoutExercise
    form_class = WorkoutExerciseForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.workout_id = None
        self.enabled_metric_fields_by_exercise = get_enabled_metric_fields_by_exercise()
        self.default_metric_values_by_exercise = get_default_metric_values_by_exercise(self.enabled_metric_fields_by_exercise)
        self.notes_by_exercise = get_notes_by_exercise()

    def dispatch(self, request, *args, **kwargs):
        self.workout_id = kwargs["workout_id"]
        return super().dispatch(request, *args, **kwargs)
    
    def get_initial(self):
        initial = super().get_initial()
        initial["exercise"] = None
        return initial
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["workout"] = Workout.objects.get(id=self.workout_id)
        context["all_metric_fields"] = Exercise.get_all_metric_fields()
        context["enabled_metric_fields_by_exercise"] = self.enabled_metric_fields_by_exercise
        context["default_metric_values_by_exercise"] = self.default_metric_values_by_exercise
        context["notes_by_exercise"] = self.notes_by_exercise
        return context
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.workout_id = self.workout_id
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("workout", kwargs={"pk": self.workout_id})
    

class WorkoutUpdateExerciseView(generic.UpdateView):
    template_name = "workouttracker/workout/workout_exercise_form.html"
    model = WorkoutExercise
    form_class = WorkoutExerciseForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["workout"] = self.object.workout
        return context

    def get_success_url(self):
        return reverse_lazy("workout", kwargs={"pk": self.object.workout.id})


class WorkoutIncrementExerciseSetsView(generic.View):
    def post(self, request, *args, **kwargs):
        workout_exercise = WorkoutExercise.objects.get(id=kwargs["pk"])
        workout_exercise.sets += 1
        workout_exercise.save()
        return HttpResponse(workout_exercise.sets)
    

class WorkoutEndView(generic.UpdateView):
    template_name = "workouttracker/workout/workout_exercise_form.html"
    model = Workout
    form_class = WorkoutEndForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.end_dt = timezone.now()
        obj.save()
        return super().form_valid(form)
    

class WorkoutPreviousListView(generic.ListView):
    template_name = "workouttracker/workout/workout_previous_list.html"
    model = Workout
    queryset = Workout.objects.filter(end_dt__isnull=False).order_by("-start_dt")
    

class ExerciseListView(generic.ListView):
    template_name = "workouttracker/edit/exercise_list.html"
    model = Exercise


class ExerciseCreateView(generic.CreateView):
    template_name = "workouttracker/edit/exercise_form.html"
    model = Exercise
    form_class = ExerciseForm
    success_url = reverse_lazy("exercise_list")


class ExerciseUpdateView(generic.UpdateView):
    template_name = "workouttracker/edit/exercise_form.html"
    model = Exercise
    form_class = ExerciseForm
    success_url = reverse_lazy("exercise_list")


class ExerciseDeleteView(generic.DeleteView):
    template_name = "workouttracker/edit/exercise_delete.html"
    model = Exercise
    success_url = reverse_lazy("exercise_list")


class StatisticsView(generic.TemplateView):
    template_name = "workouttracker/statistics/statistics.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["exercises"] = Exercise.objects.all()
        context["weight_data_points"] = [(w.start_dt.strftime("%m-%d-%Y %H:%M"), w.weight) for w in Workout.objects.filter(weight__isnull=False)]
        context["length_data_points"] = [(w.start_dt.strftime("%m-%d-%Y %H:%M"), w.get_length()) for w in Workout.objects.filter(end_dt__isnull=False)]
        return context


class StatisticsExerciseDataPointsView(generic.View):
    def get(self, request, *args, **kwargs):
        exercise = Exercise.objects.get(id=kwargs["pk"])
        workout_exercises = WorkoutExercise.objects.filter(exercise=exercise)
        data_points = {capitalise_and_underscore_to_space(metric_field_name): [(workout_exercise.workout.start_dt.strftime("%m-%d-%Y %H:%M"), metric_value.seconds if metric_field_name == "duration" else metric_value) for workout_exercise in workout_exercises if (metric_value := getattr(workout_exercise, metric_field_name)) is not None] for metric_field_name in exercise.get_enabled_metric_fields() + ["sets"]}
        return JsonResponse(data_points)

workouttracker/templates/workouttracker/workout/workout.html
{% extends "base.html" %}
{% load workout_extras %}

{% block main %}
    <h4>Workout {% if object.is_complete %}from {{ object.start_dt|date:'d-m-Y H:i' }} to {{ object.end_dt|date:'d-m-Y H:i' }}{% else %}starting at {{ object.start_dt|date:'d-m-Y H:i' }}{% endif %}</h4>
    {% if not object.is_complete %}
        <a class="btn btn-secondary w-100 mb-2" href="{% url 'workout_add_exercise' workout_id=object.id %}">Add exercise</a>
    {% endif %}
    <div class="row">
        {% for workout_exercise in object.workoutexercise_set.all %}
            <div class="col-12">
                <div {% if not object.is_complete %}role="button"{% endif %} class="row mx-0 mb-2 bg-light text-decoration-none{% if not object.is_complete %} workout-exercise-row{% endif %}" data-update-url="{% url 'workout_update_exercise' pk=workout_exercise.pk %}" data-workout-exercise-id="{{ object.id }}">
                    <div class="col-3 d-flex justify=content-center" style="display: flex; justify-content: center">
                        <img src="{{ workout_exercise.exercise.get_image_url }}" class="w-100" style="aspect-ratio: 1/1; object-fit: contain"></img>
                    </div>
                    <div class="col py-2">
                        <h5 class="text-dark text-decoration-none fw-bold">{{ workout_exercise.exercise.name }}</h5>
                        {% for metric_field_name, metric_value in workout_exercise.get_metric_values.items %}
                            <p class="text-dark text-decoration-none mb-1">{{ metric_field_name|capitalise_and_underscore_to_space }}: {{ metric_value }}</p>
                        {% endfor %}
                    </div>
                    <div class="col-auto">
                        <h5 class="text-dark text-decoration-none fw-bold text-end mb-1"><span class="text-nowrap">Sets: <span class="set-counter">{{ workout_exercise.sets }}</span></span></h5>
                        {% if not object.is_complete %}<button class="set-increment-button btn btn-primary py-1 w-100" data-set-increment-url="{% url 'workout_increment_exercise_sets' pk=workout_exercise.pk %}">+</button>{% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if object.is_complete %}
        {% if object.weight %}
            <h5>Weight at end of workout: <span class="fw-bold">{{ object.weight }} kgs</span></h5>
        {% endif %}
    {% else %}
        <a class="btn btn-success w-100" href="{% url 'workout_end' pk=object.id %}">End workout</a>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script>
        $(".set-increment-button").click(function(e) {
            e.stopPropagation();
            const setIncrementButton = $(this)
            const workoutExerciseRow = setIncrementButton.closest(".workout-exercise-row")
            const setCounter = workoutExerciseRow.find(".set-counter")
            setIncrementButton.prop("disabled", true)
            $.post(setIncrementButton.data("set-increment-url"), {csrfmiddlewaretoken: "{{ csrf_token }}"}, function(newSetCount) {
                setCounter.text(newSetCount)
                setIncrementButton.prop("disabled", false)
            });
        });

        $(".workout-exercise-row").click(function() {
            window.location = $(this).data("update-url")
        });
    </script>
{% endblock %}

workouttracker/templates/workouttracker/workout/workout_exercise_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
    <h5>Workout starting at {{ workout.start_dt|date:'d-m-Y H:i' }}</h5>
    {% if object %}
        <h6>Updating {{ object }}</h6>
    {% endif %}
    <form id="workout_exercise_form" method="post">
        {% crispy form %}
    </form>
{% endblock %}

{% block scripts %}
    {% if not self.object %}
        {{ enabled_metric_fields_by_exercise|json_script:"enabled_metric_fields_by_exercise" }}
        {{ default_metric_values_by_exercise|json_script:"default_metric_values_by_exercise" }}
        {{ notes_by_exercise|json_script:"notes_by_exercise" }}
        <script>
            const enabledMetricFieldsByExercise = JSON.parse(document.getElementById('enabled_metric_fields_by_exercise').textContent);
            const defaultMetricValuesByExercise = JSON.parse(document.getElementById('default_metric_values_by_exercise').textContent);
            const notesByExercise = JSON.parse(document.getElementById('notes_by_exercise').textContent);
            console.log(notesByExercise)
            notesDiv = $("#div_notes")
            $("#id_exercise").change(function() {
                let enabledMetricFields = []
                let defaultMetricValues = {}
                let notes = ""
                const exerciseID = $(this).val()
                if (exerciseID) {
                    enabledMetricFields = enabledMetricFieldsByExercise[exerciseID]
                    defaultMetricValues = defaultMetricValuesByExercise[exerciseID]
                    notes = notesByExercise[exerciseID]
                }
                {% for metric_field in all_metric_fields %}
                    $("#id_{{ metric_field }}").val("")
                    if (enabledMetricFields.includes("{{ metric_field }}")) {
                        $("#div_id_{{ metric_field }}").removeClass("d-none")
                        $("#id_{{ metric_field }}").prop("required", true)
                        if (Object.keys(defaultMetricValues).includes("{{ metric_field }}")) {
                            $("#id_{{ metric_field }}").val(defaultMetricValues["{{ metric_field }}"])
                        }
                    }
                    else {
                        $("#div_id_{{ metric_field }}").addClass("d-none")
                        $("#id_{{ metric_field }}").prop("required", false)
                    }
                {% endfor %}
                notesDiv.html(notes).toggleClass("d-none", !notes.length)
            }).change();
        </script>
    {% endif %}
{% endblock %}

workouttracker/templates/workouttracker/workout/workout_previous_list.html
{% extends "base.html" %}

{% block main %}
    {% for workout in object_list %}
        <a class="btn btn-light w-100 mb-1" href="{% url 'workout' pk=workout.pk %}">{{ workout }}</a>
    {% endfor %}
{% endblock %}